id: P4C667BBD
initial_creation_type: input
source_metadata:
  Title: Bibliotheca Buddhica (Mahāvyutpatti)
  Editor: Minaev I.P & Mironov, N.D
  Publisher: Bibliotheca Buddhica
  Place of Publication: St. Petersburg
  Year: '1910'
  Mahāvyutpatti:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2008'
    Proof Reader: Milan Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:37:06.593237'
last_modified_at: '2022-03-08T16:37:06.593247'
